/**
 *  Copyright (c) 2007-2010 CyberInfrastructure and Geospatial
 *  Information Laboratory (CIGI), University of Illinois at
 *  Urbana-Champaign, All Rights Reserved.
 */

// This file was auto-generated by SimpleGrid SkeletonGen utility
// Built on : Jan 3, 2011
package org.simplegrid.app.dms;

public class DMSSkeleton implements DMSSkeletonInterface {
	public org.simplegrid.app.dms.GetResultResponse getResult
	(org.simplegrid.app.dms.GetResult getResult0)
	{
		org.simplegrid.app.dms.DMS dms0= new org.simplegrid.app.dms.DMS();
		java.lang.String r = dms0.getResult(getResult0.getArgs0(), getResult0.getArgs1(), getResult0.getArgs2());
		org.simplegrid.app.dms.GetResultResponse res = new org.simplegrid.app.dms.GetResultResponse();
		res.set_return(r);
		return res;
	}

	public org.simplegrid.app.dms.VisualizeResponse visualize
	(org.simplegrid.app.dms.Visualize visualize1)
	{
		org.simplegrid.app.dms.DMS dms1= new org.simplegrid.app.dms.DMS();
		java.lang.String r = dms1.visualize(visualize1.getArgs0(), visualize1.getArgs1(), visualize1.getArgs2());
		org.simplegrid.app.dms.VisualizeResponse res = new org.simplegrid.app.dms.VisualizeResponse();
		res.set_return(r);
		return res;
	}

	public org.simplegrid.app.dms.SubmitResponse submit
	(org.simplegrid.app.dms.Submit submit2)
	{
		org.simplegrid.app.dms.DMS dms2= new org.simplegrid.app.dms.DMS();
		java.lang.String r = dms2.submit(submit2.getArgs0(), submit2.getArgs1(), submit2.getArgs2(), submit2.getArgs3(), submit2.getArgs4());
		org.simplegrid.app.dms.SubmitResponse res = new org.simplegrid.app.dms.SubmitResponse();
		res.set_return(r);
		return res;
	}

	public org.simplegrid.app.dms.GetStatusResponse getStatus
	(org.simplegrid.app.dms.GetStatus getStatus3)
	{
		org.simplegrid.app.dms.DMS dms3= new org.simplegrid.app.dms.DMS();
		java.lang.String r = dms3.getStatus(getStatus3.getArgs0());
		org.simplegrid.app.dms.GetStatusResponse res = new org.simplegrid.app.dms.GetStatusResponse();
		res.set_return(r);
		return res;
	}

}
